#ifndef QCANOPENMASTER_GLOBAL_H
#define QCANOPENMASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QCANOPENMASTER_LIBRARY)
#define QCANOPENMASTER_EXPORT Q_DECL_EXPORT
#else
#define QCANOPENMASTER_EXPORT Q_DECL_IMPORT
#endif

#endif // QCANOPENMASTER_GLOBAL_H
